version: '3.9'

services:
  backend:
    build: ./backend
    container_name: desafio_backend_massagem
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:16
    container_name: postgres_massagem
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: massagem
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma:
    build:
      context: ./backend
      dockerfile: Dockerfile.prisma
    container_name: prisma_massagem
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    entrypoint: [""]


volumes:
  postgres_data:
