version: '3.9'

services:
  backend:
    build: ./backend
    container_name: desafio_backend_massagem
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    command: npm run dev
