# Imagem base
FROM node:22.17.1-alpine

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos package.json e package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia os demais arquivos
COPY . .

# Expõe a porta
EXPOSE 3000

# Comando padrão
CMD ["npm", "run", "dev"]
